baseURL = 'https://vindalebynight.netlify.app/'
languageCode = 'en-us'
title = 'Vindale'
theme = 'hugo-theme-learn'
disableKinds = ["taxonomyTerm" ]

[outputs]
home = [ "HTML", "RSS", "JSON"]
[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      